### ISSUE TITLE
Federation: Support deploying federation control plane on non-cloud environment

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#101]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shashidharatd](https://github.com/shashidharatd)**
_Thursday Jan 26, 2017 at 18:42 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/40536_

----

There may be scenarios where there is a need to federate k8s clusters on private-cloud (on-premise) environments.
Listed below are some of the tasks to achieve the scenario above

- [x] Federation control plane deployment itself should be able to be deployed in non-cloud environments. #40516
- [x] Should be possible to disable persistent storage for etcd. #40862
- [x] Ability to configure desired DNS provider. Public DNS servers (AWS Route53/ Google CloudDNS) or Private DNS servers (e.g. CoreDNS) #40528 
- [x] Document Federation CoreDNS support. https://github.com/kubernetes/kubernetes.github.io/pull/2810
- [x] coredns federation provider should support etcd with TLS #47049
- [ ] Document using hosted DNS providers (AWS Route53/ Google CloudDNS) in non-cloud environments.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Thursday Jan 26, 2017 at 18:43 GMT_

----

@marun, Please feel free to correct or add any additional points to this issue.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Thursday Jan 26, 2017 at 18:54 GMT_

----

This issue will partly address the `deployment` part of federation on non-google clouds as described in #39870

**Comment by irfanurrehman** [comment]
<a href="https://github.com/marun"><img src="https://avatars3.githubusercontent.com/u/451477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marun](https://github.com/marun)**
_Thursday Jan 26, 2017 at 23:36 GMT_

----

I think this issue can serve as an umbrella to track issues targeting improved support for non-cloud deployments with ``kubefed``.  Rather than conflating the work involved, work items can be tracked and discussed separately:

 - [`kubefed init` should also work on clusters without a service load balancer implementation](https://github.com/kubernetes/kubernetes/issues/39271)

 - [Should be possible to disable persistent storage for etcd](https://github.com/kubernetes/kubernetes/issues/40617)

 - [Enable dnsaas configuration for non-cloud deployments](https://github.com/kubernetes/kubernetes/issues/40620)

 - [Should allow DNSaaS integration to be disabled](https://github.com/kubernetes/kubernetes/issues/40616)

- [Document Federation CoreDNS support.](https://github.com/kubernetes/kubernetes.github.io/issues/2197)

**Comment by irfanurrehman** [comment]
<a href="https://github.com/marun"><img src="https://avatars3.githubusercontent.com/u/451477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marun](https://github.com/marun)**
_Thursday Jan 26, 2017 at 23:46 GMT_

----

cc: @madhusudancs @kubernetes/sig-federation-misc

**Comment by irfanurrehman** [comment]
<a href="https://github.com/mattymo"><img src="https://avatars2.githubusercontent.com/u/1229061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattymo](https://github.com/mattymo)**
_Friday Mar 17, 2017 at 14:17 GMT_

----

https://github.com/kubernetes/kubernetes/issues/42995 should be considered for the list

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Wednesday May 03, 2017 at 13:35 GMT_

----

/assign

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liqlin2015"><img src="https://avatars3.githubusercontent.com/u/10703772?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liqlin2015](https://github.com/liqlin2015)**
_Monday Aug 07, 2017 at 07:43 GMT_

----

Is there any way we can use a local service load balancer for federation service?

And is there any plan to support services only with external IP? Currently in the `dns.go:wantsDNSRecords()` function, we hard coded to only support `v1.ServiceTypeLoadBalancer` type of services. Can we use external IP as another option for on-prem clusters?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Monday Aug 07, 2017 at 10:56 GMT_

----

what is the meaning of `local service load balancer`.

Currently only loadbalancer type services are supported for federated services. Currently there is no other option available as we know, which works.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/luckyfengyong"><img src="https://avatars3.githubusercontent.com/u/8002217?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [luckyfengyong](https://github.com/luckyfengyong)**
_Monday Aug 07, 2017 at 17:52 GMT_

----

@shashidharatd In the doc of federation service discovery, it is mentioned as follows 

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8002217/29038662-81ad5fc8-7b76-11e7-965a-9d1073d86477.png">

After checking the codes we found only when a service is created with the type of Loadbalancer, the DNS record of the service is created in federation dns service. Just wondering what if the service is created with exnternalip. For that case, can we also ask federation dns service to create the DNS record?

Basically our use case is just like what this ticket is described to run cluster federation within on-prem environment. However we find there is no out-of-box external loadbalancer service available.

Therefore we will need either ask dns server of cluster federation supporting the service with externalip, or have a out-of-box loadbalancer service (just like coredns as out-of-box dns server of cluster federation)

Any suggestion?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Sep 08, 2017 at 02:19 GMT_

----

Required for GA of federation.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/luxas"><img src="https://avatars1.githubusercontent.com/u/5442475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [luxas](https://github.com/luxas)**
_Friday Sep 08, 2017 at 11:29 GMT_

----

@quinton-hoole Any relevant design doc/proposal for this issue/feature request?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Sep 14, 2017 at 17:20 GMT_

----

@luxas Nothing beyond what it linked in this issue, that I am aware of.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Wednesday Sep 27, 2017 at 14:13 GMT_

----

All the tasks we envisioned are complete and hence closing this issue. If anyone feels this issue needs to be kept open for additional tasks, please feel free to do so.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/luxas"><img src="https://avatars1.githubusercontent.com/u/5442475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [luxas](https://github.com/luxas)**
_Wednesday Sep 27, 2017 at 15:31 GMT_

----

@shashidharatd Where is the documentation for this feature?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Wednesday Sep 27, 2017 at 15:52 GMT_

----

@luxas, here is the documentation for running federation with CoreDNS as dns provider. https://kubernetes.io/docs/tasks/federation/set-up-coredns-provider-federation.
In non-cloud environments, we could also use hosted DNS providers such as AWS Route53 or Google Cloud-DNS by specifying the dns-provider configuration as secret to `kubefed init`. 

I agree there is no detailed document for user explaining how to use the hosted DNS providers (AWS Route53/Google Cloud-DNS). We shall add this document in the upcoming release.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Wednesday Sep 27, 2017 at 15:57 GMT_

----

Added a new item to document explaining how to use the hosted DNS providers in non-cloud environments and so reopened this issue.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/luxas"><img src="https://avatars1.githubusercontent.com/u/5442475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [luxas](https://github.com/luxas)**
_Wednesday Sep 27, 2017 at 16:09 GMT_

----

Thanks!

**Comment by irfanurrehman** [comment]
<a href="https://github.com/pilsy"><img src="https://avatars1.githubusercontent.com/u/2503364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pilsy](https://github.com/pilsy)**
_Sunday Oct 15, 2017 at 14:48 GMT_

----

Any answer to https://github.com/kubernetes/kubernetes/issues/40536#issuecomment-320733514 ?

**Comment by irfanurrehman** [comment]
cc @shashidharatd

**Comment by moonek** [comment]
I want to know the current situation.
I am interested in the on-premise environment.
The only dns-provider in on-premise understood as `CoreDNS`.
The service type for cross-cluster service discovery is documented as `Loadbalancer` and `External IP`.
![image](https://user-images.githubusercontent.com/7972724/33871204-d69d7148-df54-11e7-8fcb-7821648f6284.png)
However, the ServiceType in the CoreDNS Setup Guide is written as `LoadBalancer` or `NodePort`.
![image](https://user-images.githubusercontent.com/7972724/33871207-dba23f48-df54-11e7-88ea-511b5990fc6c.png)

It is mentioned that only `LoadBalancer` is possible in this issue.
Which is right? I am very confused.

**Comment by shashidharatd** [comment]
If you have a user service that need to be federated across clusters (multi-cluster scenario). The service type has to be a LoadBalancer type in-order to be able to do federated service discovery across clusters.

Now coming to the documents you are referring. The mention is about CoreDNS service. CoreDNS server/service itself runs within a kubernetes cluster and the guide is talking about setting up CoreDNS service.

In some of the on-prem environments like openstack the LoadBalancer type service is possible and on the on-prem environments which lack LoadBalancer type service federated service discovery is not possible through federation currently

**Comment by dholt** [comment]
Any updates on the last item (Document using hosted DNS providers (AWS Route53/ Google CloudDNS) in non-cloud environments.)?

**Comment by shashidharatd** [comment]
@dholt, Thanks for asking. We need some volunteers to do that. I would create a separate issue for that item. Would you be interested in taking up some portion?

**Comment by shashidharatd** [comment]
Created a separate [issue](https://github.com/kubernetes/federation/issues/250) to track the above incomplete work mentioned in https://github.com/kubernetes/federation/issues/101#issuecomment-373570599

**Comment by shashidharatd** [comment]
There is some work done by @marun as commented in this https://github.com/kubernetes/kubernetes/issues/40620#issue-203719292 related to configuraing Google Cloud DNS in non-google environment.

**Comment by dholt** [comment]
I would be happy to try and help document. I don't think I'm qualified to help implement however, and it looked to me from browsing the code like this feature may be implemented for Google Cloud DNS but not AWS Route53?
