### ISSUE TITLE
federation services: known issues

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#141]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Monday May 22, 2017 at 19:18 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/46240_

----

Documenting the list of known issues with federated services:

- [ ] Should configure CNAME records instead of A records on AWS: https://github.com/kubernetes/kubernetes/issues/35637
- [ ] Duplicate resource record errors with Route53: https://github.com/kubernetes/kubernetes/issues/42131
- [ ] Remove DNS entries when a cluster is removed from federation: https://github.com/kubernetes/kubernetes/issues/36657
- [ ] Fail to create DNS records for multizone clusters: https://github.com/kubernetes/kubernetes/issues/35997

cc @kubernetes/sig-federation-bugs @shashidharatd @madhusudancs

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Monday May 22, 2017 at 19:42 GMT_

----

> Should configure CNAME records instead of A records on AWS: #35637

Can we please characterize the first issue correctly? We already know that's not even the right solution. I would characterize it along the lines of "Ensure that resolved IP addresses don't go out of sync with the ELBs on AWS" or something like that? I think the linked issue also does a good job of explaining the issue.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Saturday Sep 02, 2017 at 00:46 GMT_

----

Added priority.  Need to fix this before Federation GA.

**Comment by irfanurrehman** [comment]
cc @nikhiljindal

**Comment by nikox94** [comment]
@madhusudancs I just re-read your comments on the AWS DNS issue. After having experimented for awhile, it seems to me that we should not sweep under the carpet the fact that we effectively want to dns-load-balance multiple DNS endpoints (one for every cluster for every federated service).

Let's have the following:

Let's say we have a federation deployment with the following clusters: aws1, aws2, gcp1, gcp2. Let's say we deploy a federated service named `tom`. What we effectively want is a DNS endpoint called 
```
service.namespace.federation.svc.my.domain.com
```
that will "load-balance" fairly between the clusters, i.e. when we call it we want it to somehow split traffic so that each cluster of aws1, aws2, gcp1, gcp2 gets hit by some percentage of traffic (25% or other depending on configs).

If my understanding of the above is correct, that means we effectively need something like [this](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted). I am not sure if GCP CloudDNS, CoreDNS ([this](https://coredns.io/plugins/loadbalance/)), etc. have similar functionalities.

Ideally we can have CNAMEs or A records of the form
```
service.aws1.namespace.federation.svc.my.domain.com
service.aws2.namespace.federation.svc.my.domain.com
service.gcp1.namespace.federation.svc.my.domain.com
service.gcp2.namespace.federation.svc.my.domain.com
```
And then we can "load-balance" them bu creating an appropriate routing record called
```
service.namespace.federation.svc.my.domain.com
```
which will represent the service and will load-balance between the 4 endpoints above.

What do you think? @madhusudancs
