### ISSUE TITLE
federation: Known issues

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#88]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Friday Dec 16, 2016 at 19:52 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/38893_

----

Compiling a list of high level known issues that customers should be aware of while deciding to use federation:

- [x] No way to disable specific APIs (#38593)
- [ ] Alpha APIs are enabled by default (https://github.com/kubernetes/kubernetes/issues/44291)
- [ ] No upgrade testing (#38537)
- [x] No kubectl tests (https://github.com/kubernetes/kubernetes/issues/32826)
- [x] Not all e2e tests are green (https://github.com/kubernetes/kubernetes/issues/37105)
- [ ] Unclear auth story (https://github.com/kubernetes/kubernetes/issues/35254)
- [ ] Not all API resources are supported in federation (http://kubernetes.io/docs/user-guide/federation/ lists the supported resources)
- [ ] Need to design HA federation control plane (https://github.com/kubernetes/features/issues/104)

cc @kubernetes/sig-federation-misc

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Friday Dec 16, 2016 at 19:52 GMT_

----

cc @madhusudancs 

Please feel free to add anything that I missed.
I plan to keep this as a running list. Will keep adding/removing stuff as we discover/fix issues

**Comment by irfanurrehman** [comment]
<a href="https://github.com/valichek"><img src="https://avatars0.githubusercontent.com/u/7127622?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [valichek](https://github.com/valichek)**
_Monday Dec 19, 2016 at 10:22 GMT_

----

I tried to run federation control plane on aws but got many issues recently.
1. script https://github.com/kubernetes/kubernetes/blob/v1.5.1/federation/deploy/deploy.sh doesn't support `aws` provider
2. Tried to use old way (deploying manifests one by one), got `federation-apiserver`and `federation-controller-manager` running,  but then it resulted to `error in fetching secret: secrets "federation-apiserver-kubeconfig" not found` at `federation-controller-manager` container, no description for this secret found.
3. Couldn't find sources of `gcr.io/madhusudancs-containers/federation-charts` image

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Tuesday Dec 20, 2016 at 04:34 GMT_

----

@valichek Could you try using `kubefed` - http://kubernetes.io/docs/admin/federation/kubefed/?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/valichek"><img src="https://avatars0.githubusercontent.com/u/7127622?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [valichek](https://github.com/valichek)**
_Thursday Dec 22, 2016 at 12:52 GMT_

----

@madhusudancs getting following errors when starting federation services with kubefed
```
Failed to attach volume "pvc-xxxx" on node "xxxx.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-xxxx is not 'available'
```
First time there was a message for ec-2 instance: "One or more volumes attached to this instance is impaired". And volume stuck in attaching. 
When tried again got the same error, but volume have been attached.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/valichek"><img src="https://avatars0.githubusercontent.com/u/7127622?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [valichek](https://github.com/valichek)**
_Thursday Dec 22, 2016 at 14:38 GMT_

----

well, after some time, `apiserver` turned to be running, but not `controller-manager`, 

```
Cloud provider could not be initialized: could not init DNS provider "google-clouddns": 
google: could not find default credentials. 
See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I have check `kubefed` sources and found that `--dns-provider` and many other things are hardcoded and not configurable
https://github.com/kubernetes/kubernetes/blob/04a74570323eae3fc843ca7a6c34c28ada2847a9/federation/pkg/kubefed/init/init.go#L477

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Thursday Dec 22, 2016 at 16:51 GMT_

----

@valichek 

> I have check kubefed sources and found that --dns-provider and many other things are hardcoded and not configurable
https://github.com/kubernetes/kubernetes/blob/04a74570323eae3fc843ca7a6c34c28ada2847a9/federation/pkg/kubefed/init/init.go#L477

That's an old commit. 

If you want to use AWS Route53 instead of Google Cloud DNS, pass `--dns-provider=aws-route53` to `kubefed init`.

For now, you can configure everything you want by just editing the deployments directly after running `kubefed init`: `kubectl --context=<host-cluster> --namespace=federation-system edit deployment federation-apiserver` or `kubectl --context=<host-cluster> --namespace=federation-system edit deployment federation-controller-manager`.

We are collecting a list of things we need to make configurable. What else would you like to configure?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/valichek"><img src="https://avatars0.githubusercontent.com/u/7127622?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [valichek](https://github.com/valichek)**
_Thursday Dec 22, 2016 at 17:29 GMT_

----

@madhusudancs well, for now it looks that I need to configure CIDR, I used kube-aws tool to run the cluster, and have following options:
`instanceCIDR: "10.0.16.0/20"`
`serviceCIDR: "10.128.0.0/20"`
`podCIDR: "10.128.16.0/20"`
`dnsServiceIP: 10.128.0.10`

If I understand the config properly, I have to change from `--service-cluster-ip-range=10.0.0.0/16"`
to `--service-cluster-ip-range=10.128.112.0/20"`, or should I leave it same as for cluster - `serviceCIDR: "10.128.0.0/20"` ?

And thank you.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/valichek"><img src="https://avatars0.githubusercontent.com/u/7127622?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [valichek](https://github.com/valichek)**
_Thursday Dec 22, 2016 at 17:44 GMT_

----

And `--dns-zone-id` too

**Comment by irfanurrehman** [comment]
<a href="https://github.com/rbtcollins"><img src="https://avatars2.githubusercontent.com/u/499678?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rbtcollins](https://github.com/rbtcollins)**
_Tuesday Jan 24, 2017 at 20:08 GMT_

----

@madhusudancs Is there a means to move the federation control plane to another cluster? We're trying to avoid in-place upgrades of k8s clusters - should I file a separate bug on kubefed?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Wednesday Jan 25, 2017 at 20:31 GMT_

----

@valichek `--service-cluster-ip-range` in federation API server does nothing. So just leave the defaults as is. In the next release (v1.6), we are removing that flag from federation.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Wednesday Jan 25, 2017 at 20:34 GMT_

----

@rbtcollins It is possible, but you have to orchestrate that manually. You just need to start the federation API server and controller manager pods in the new cluster and attach the etcd volume from the old cluster to those pods.

Please feel free to file an issue for `kubefed`. We will look into it when we design/implement HA support for federation control plane via kubefed.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Sep 08, 2017 at 02:32 GMT_

----

We can update this issue to track all of the remaining GA items.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/xtophs"><img src="https://avatars1.githubusercontent.com/u/8771377?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xtophs](https://github.com/xtophs)**
_Tuesday Oct 24, 2017 at 12:25 GMT_

----

Because deploy.sh is specific to gce and gke, federation e2e tests cannot run [as documented](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#federation-e2e-tests) on Azure (or aws). 

Other documentation on how to run federation tests manually is not available

**Comment by irfanurrehman** [comment]
cc @nikhiljindal

**Comment by luceos** [comment]
/reopen
/remove-lifecycle rotten

Isn't this issue about the state of federation?
