### ISSUE TITLE
Federated Deployments: known issues

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#98]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Tuesday Jan 17, 2017 at 03:01 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/39987_

----

Documenting the list of known issues with federated deployments:

- [ ] Enable federation-apiserver kubectl tests for deployments: https://github.com/kubernetes/kubernetes/issues/39985.
- [ ] Figure out a path to GA for FederatedReplicaSetPreferences.
- [ ] Verify that rebalancing works and add a test for that: https://github.com/kubernetes/kubernetes/issues/33312
- [ ] Document how rebalancing works: https://github.com/kubernetes/kubernetes.github.io/issues/1362
- [ ] Handle rollbacks: https://github.com/kubernetes/kubernetes/issues/37570
- [ ] Update to use apps group version: https://github.com/kubernetes/kubernetes/issues/52123

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Tuesday Jan 17, 2017 at 03:01 GMT_

----

cc @kubernetes/sig-federation-misc @mwielgus
Feel free to add anything that I missed

**Comment by irfanurrehman** [comment]
<a href="https://github.com/uiansol"><img src="https://avatars1.githubusercontent.com/u/1727838?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [uiansol](https://github.com/uiansol)**
_Monday Apr 03, 2017 at 19:40 GMT_

----

@nikhiljindal Are this issues still opened? Is someone working in this tasks?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Thursday Apr 20, 2017 at 22:15 GMT_

----

@uiansol Yes all the issues are still open. There are owners for some. 
I dont think anyone is working on #33312 or #33312 but please post on the individual issue if you want to work on any.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Thursday Apr 20, 2017 at 22:24 GMT_

----

cc @perotinus

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Apr 21, 2017 at 14:21 GMT_

----

@nikhiljindal You pasted the same issue number twice above.  Did you mean #33312 and #37570?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Thursday Apr 27, 2017 at 18:20 GMT_

----

@perotinus said he will take up https://github.com/kubernetes/kubernetes/issues/37570

**Comment by irfanurrehman** [comment]
<a href="https://github.com/perotinus"><img src="https://avatars1.githubusercontent.com/u/5122391?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [perotinus](https://github.com/perotinus)**
_Friday Aug 04, 2017 at 18:41 GMT_

----

I'm not working on this ATM, so someone else should feel free to take it on.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Friday Sep 22, 2017 at 19:24 GMT_

----

Added moving to apps group version https://github.com/kubernetes/kubernetes/issues/52123 to the list.

**Comment by irfanurrehman** [comment]
cc @nikhiljindal
