### ISSUE TITLE
federation ingress: known issues

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#99]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Tuesday Jan 17, 2017 at 03:15 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/39989_

----

Documenting the list of known issues with federated ingress:

Issues that need to be fixed soon:
- [x] Need to create a firewall rule. Users will have to create it manually pre 1.5. Document it. Create it in the test for now and get the tests to turn green (https://github.com/kubernetes/kubernetes/pull/37571). In 1.6, create it automatically in the controller (https://github.com/kubernetes/kubernetes/issues/37306).
- [ ] Verify (add a test) and document that users need to create a static IP themselves (by running `gcloud compute addresses create kubernetes-ingress --global`) for HTTP load balancer.
- [ ] GCP Ingress does not work for clusters in the same zone (https://github.com/kubernetes/kubernetes/issues/47565)
- [ ] Resource leak due to race condition with service controller (https://github.com/kubernetes/kubernetes/issues/52315)

Longer term:
- [ ] Support federated ingress outside GCP. https://github.com/kubernetes/kubernetes/issues/51806

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Tuesday Jan 17, 2017 at 03:15 GMT_

----

cc @kubernetes/sig-federation-misc @madhusudancs @allannaim
Feel free to add anything that I might have missed.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/clenimar"><img src="https://avatars3.githubusercontent.com/u/410648?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clenimar](https://github.com/clenimar)**
_Thursday May 18, 2017 at 14:05 GMT_

----

it seems that the two short-term issues have already been fixed.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/uiansol"><img src="https://avatars1.githubusercontent.com/u/1727838?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [uiansol](https://github.com/uiansol)**
_Wednesday May 31, 2017 at 19:48 GMT_

----

@nikhiljindal Who is working on Support federated ingress outside GCP? Is there a proposal for this?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Jun 01, 2017 at 00:37 GMT_

----

@uiansol I'm not aware of anyone currently actively working on it, but Amazon, CoreOS and Ticketmaster have recently done some integration work between Kubernetes Ingress and AWS ALB, that lays some good groundwork to federate on top of this.

https://coreos.com/blog/alb-ingress-controller-intro

I would be happy to write up a design if anyone can offer some developers to implement it.  I don't think that it would require much work to implement federated ingress across multiple AWS-only clusters.  Multi-cloud/hybrid federated ingress is a bit harder, but also doable if anyone is interested enough to implement it.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/uiansol"><img src="https://avatars1.githubusercontent.com/u/1727838?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [uiansol](https://github.com/uiansol)**
_Thursday Jun 01, 2017 at 00:54 GMT_

----

@quinton-hoole Good to know, we have a "gang of 4" to work. =)
If you write up the design we will be glad to work on that. We have been PM docs and trying to help in some bugs.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Jun 01, 2017 at 01:45 GMT_

----

@uiansol Great.  I will try to get a design out in the next two weeks.  I have a draft already.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/gurvindersingh"><img src="https://avatars2.githubusercontent.com/u/186077?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gurvindersingh](https://github.com/gurvindersingh)**
_Tuesday Jun 20, 2017 at 06:19 GMT_

----

@quinton-hoole wondering if you have any update on the design of having ingress working outside GCP e.g. in baremetal or other cloud providers.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/henriquetruta"><img src="https://avatars2.githubusercontent.com/u/2501482?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [henriquetruta](https://github.com/henriquetruta)**
_Tuesday Jun 27, 2017 at 18:43 GMT_

----

hi @quinton-hoole are you still working on this?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Jun 30, 2017 at 18:36 GMT_

----

@henriquetruta @gurvindersingh Unfortunately I no longer have access to the doc, which I wrote while at Google, and handed over when I left.  I have asked @nikhiljindal To try to track it down, but unfortunately is has not yet been tracked down.  Any updates @nikhiljindal ?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/gurvindersingh"><img src="https://avatars2.githubusercontent.com/u/186077?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gurvindersingh](https://github.com/gurvindersingh)**
_Saturday Jul 01, 2017 at 07:19 GMT_

----

@quinton-hoole thanks for the info and good luck with the new role. I look forward to reading docs one found.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/mattbates"><img src="https://avatars3.githubusercontent.com/u/2185766?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattbates](https://github.com/mattbates)**
_Wednesday Jul 12, 2017 at 21:23 GMT_

----

@nikhiljindal @quinton-hoole We'd also be keen to read the design doc (if it can be found) and also perhaps help contribute here too. We're seeing increasing interest in cross-region/cloud federation.

/cc @munnerz

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Sep 01, 2017 at 16:38 GMT_

----

I've moved the discussion to a separate dedicated issue:

https://github.com/kubernetes/kubernetes/issues/51806

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Sep 08, 2017 at 02:24 GMT_

----

Required for federation GA.  Prioritized accordingly.

**Comment by irfanurrehman** [comment]
cc @nikhiljindal
